:production:
  :mongodb:
    :sessions:
      :default:
        :hosts: 
          - localhost:27017
        :database: representantes2

:development:
  :mongodb:
    :sessions:
      :default:
        :hosts: 
          - localhost:27017
        :database: representantes2